/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.AbstractAction;
import Main.KCKKelner;
/**
 *
 * @author Mikołaj Balcerek
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        PanelHistoria.append("Kelner: Witaj! Co sobie życzysz?" + "\n");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Wprowadzanie = new javax.swing.JFormattedTextField();
        WyślijButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        PanelHistoria = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automatyczny Kelner");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        Wprowadzanie.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Wprowadzanie.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Wprowadzanie.setText("Porozmawiaj z Kelnerem..!");
        Wprowadzanie.setToolTipText("Tutaj wpisz swoje zamówienie");
        Wprowadzanie.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Wprowadzanie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WprowadzanieFocusGained(evt);
            }
        });

        WyślijButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        WyślijButton.setText("Wyślij..");
        WyślijButton.setToolTipText("Wyślij wiadomość");
        WyślijButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        WyślijButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        WyślijButton.setInheritsPopupMenu(true);
        WyślijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyślijButtonActionPerformed(evt);
            }
        });

        PanelHistoria.setEditable(false);
        PanelHistoria.setColumns(20);
        PanelHistoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PanelHistoria.setLineWrap(true);
        PanelHistoria.setRows(5);
        PanelHistoria.setToolTipText("Historia rozmowy z Kelnerem");
        PanelHistoria.setWrapStyleWord(true);
        PanelHistoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(PanelHistoria);
        PanelHistoria.getAccessibleContext().setAccessibleParent(jLayeredPane1);

        jLayeredPane1.setLayer(Wprowadzanie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(WyślijButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(Wprowadzanie, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WyślijButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wprowadzanie, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WyślijButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        Wprowadzanie.getAccessibleContext().setAccessibleName("PanelZamówienia");
        WyślijButton.getAccessibleContext().setAccessibleName("Wyślij");
        WyślijButton.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(153, 153, 153));
        jTextPane2.setToolTipText("Wizualizacja rozmowy");
        jScrollPane2.setViewportView(jTextPane2);
        jTextPane2.getAccessibleContext().setAccessibleName("Obraz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLayeredPane1.getAccessibleContext().setAccessibleName("Grupa Rozmowy Okna");
        jPanel1.getAccessibleContext().setAccessibleName("Panel Obrazu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WprowadzanieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WprowadzanieFocusGained
         Wprowadzanie.setText("");
    }//GEN-LAST:event_WprowadzanieFocusGained

    private void WyślijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyślijButtonActionPerformed
        wprowadzonytext = Wprowadzanie.getText();
        PanelHistoria.append("Klient: " + wprowadzonytext + "\n");
        Wprowadzanie.setText("");
        Main.KCKKelner.RozpocznijOdpowiedz(wprowadzonytext);
    }//GEN-LAST:event_WyślijButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    
//CZŁOWIEK DO CZŁOWIEKA
    public String wprowadzonytext;
    
    public void PrzekazOdpowiedz(String tekst){
        PanelHistoria.append("Kelner: " + tekst + "\n");
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea PanelHistoria;
    private javax.swing.JFormattedTextField Wprowadzanie;
    private javax.swing.JButton WyślijButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}

